title:        Enclave
host:	      0.0.0.0
port:         80
url:          https://docs.enclave.io
markdown:     kramdown
highlighter:  rouge

sass:
 sass_dir: _sass
 style: :compressed

whitelist:
  - jekyll-redirect-from

plugins:
  - jekyll-redirect-from
  - jekyll-feed
